Traceback (most recent call last):
  File "/media/haithem-sattoutah/haithem/Scheduling_Roadef/./myenv/bin/rc2.py", line 1778, in <module>
    for i, model in enumerate(rc2.enumerate(block=block), 1):
  File "/media/haithem-sattoutah/haithem/Scheduling_Roadef/./myenv/bin/rc2.py", line 539, in enumerate
    model = self.compute()
  File "/media/haithem-sattoutah/haithem/Scheduling_Roadef/./myenv/bin/rc2.py", line 477, in compute
    res = self.compute_()
  File "/media/haithem-sattoutah/haithem/Scheduling_Roadef/./myenv/bin/rc2.py", line 594, in compute_
    while not self.oracle.solve(assumptions=self.sels + self.sums):
  File "/home/haithem-sattoutah/.local/lib/python3.10/site-packages/pysat/solvers.py", line 747, in solve
    return self.solver.solve(assumptions)
  File "/home/haithem-sattoutah/.local/lib/python3.10/site-packages/pysat/solvers.py", line 1610, in solve
    self.status = pysolvers.cadical103_solve(self.cadical, assumptions,
pysolvers.error: Caught keyboard interrupt

real	60m0.083s
user	59m55.107s
sys	0m3.200s
